# Jekyll Theme Settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "Bienvenido"
subtitle: "a mi blog personal"
name: "David Le칩n Fuentes"
description: "Your website description!"
locale: "es-ES"
breadcrumbs: true
search: true

# Site Author
author:
  name   : "David Le칩n Fuentes"
  bio: "Your Bio"
  avatar : "https://avatars.githubusercontent.com/u/9919?s=110&v=4"
  location: M치laga, Espa침a
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/david-le%C3%B3n-77797720b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dxvidlf"

# Social Sharing
og_image: "https://avatars.githubusercontent.com/u/9919?s=110&v=4"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Madrid
atom_feed:
  hide: true

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      classes: wide
      header:
        teaser: "/assets/images/banner.webp"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      header:
        overlay_image: "/assets/images/banner.webp"
        overlay_filter: 0.3

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
