# Jekyll Theme Settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "Bienvenido"
subtitle: "a mi blog personal"
logo: "/assets/images/logo2.webp"
name: "David León Fuentes"
description: "Transformando ideas en innovación"
locale: "es-ES"
breadcrumbs: true
search: false

# Site Author
author:
  name   : "David León Fuentes"
  bio: "Aprendiendo más cada día"
  avatar : "/assets/images/logo2.webp"
  location: Málaga, España
  email: "davidleonfuentes21@gmail.com"
  phone: "+34 123 456 789"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/david-le%C3%B3n-77797720b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dxvidlf"

# Social Sharing
og_image: "/assets/images/logo2.webp"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Madrid
atom_feed:
  hide: true

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      classes: wide
      header:
        teaser: "/assets/images/banner.webp"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      header:
        overlay_image: "/assets/images/banner.webp"
        overlay_filter: 0.45

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
